/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import br.com.Model.ModelFornecedor;
import br.com.controller.ControllerFornecedor;

/**
 *
 * @author LEANDRO
 */
public class ViewFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form ViewCliente
     */
    ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
    ModelFornecedor modelFornecedor = new ModelFornecedor();
    ArrayList<ModelFornecedor> listaModelFornecedor = new ArrayList<>();
    String salvarAlterar;

    public ViewFornecedor() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarFornecedor();
        this.habilitaDesabilitaCampos(false);
        this.LimparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InputCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InputNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InputCNPJ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        InputTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        InputEmail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaFornecedor = new javax.swing.JTable();
        BtCancelar = new javax.swing.JButton();
        BtNovo = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtDeletar = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fornecedor");

        jLabel1.setText("Codigo");

        InputCodigo.setEnabled(false);
        InputCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        InputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("CNPJ");

        InputCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCNPJActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefone");

        jLabel5.setText("E-mail");

        InputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmailActionPerformed(evt);
            }
        });

        TabelaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CNPJ", "Telefone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelaFornecedor);
        if (TabelaFornecedor.getColumnModel().getColumnCount() > 0) {
            TabelaFornecedor.getColumnModel().getColumn(0).setMinWidth(10);
            TabelaFornecedor.getColumnModel().getColumn(0).setPreferredWidth(10);
            TabelaFornecedor.getColumnModel().getColumn(2).setMinWidth(15);
            TabelaFornecedor.getColumnModel().getColumn(2).setPreferredWidth(15);
        }

        BtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/Excluir.png"))); // NOI18N
        BtCancelar.setText("Cancelar");
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        BtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/Cadastrar.png"))); // NOI18N
        BtNovo.setText("Novo");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });

        BtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/Atualizar.png"))); // NOI18N
        BtAlterar.setText("Alterar");
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/Salvar.png"))); // NOI18N
        BtSalvar.setText("Salvar");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        BtDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/delete.png"))); // NOI18N
        BtDeletar.setText("Deletar");
        BtDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputEmail)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtSalvar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(InputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(InputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(InputCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputTelefone)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCancelar)
                    .addComponent(BtNovo)
                    .addComponent(BtAlterar)
                    .addComponent(BtSalvar)
                    .addComponent(BtDeletar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNomeActionPerformed

    private void InputCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCodigoActionPerformed

    private void InputCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCNPJActionPerformed

    private void InputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEmailActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        // TODO add your handling code here:
        //BOTÃO CANCELAR
        this.habilitaDesabilitaCampos(false);
        this.LimparCampos();
        InputCodigo.setText("");
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        // BOTÃO SALVAR
        if (salvarAlterar.equals("novo")) {

            modelFornecedor.setNomeFornecedor(this.InputNome.getText());
            modelFornecedor.setCnpjFornecedor(this.InputCNPJ.getText());
            modelFornecedor.setTelefoneFornecedor(this.InputTelefone.getText());
            modelFornecedor.setEmailFornecedor(this.InputEmail.getText());

            if (controllerFornecedor.salvarFornecedorController(modelFornecedor) > 0) {
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                //CARREGAR CLIENTES NA TABELA
                mostrarFornecedor();
                this.habilitaDesabilitaCampos(false);
                this.LimparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar!");
            }

        } else {
            //Mudar aqui
            modelFornecedor.setIdFornecedor(Integer.parseInt(this.InputCodigo.getText()));
            modelFornecedor.setNomeFornecedor(this.InputNome.getText());
            modelFornecedor.setCnpjFornecedor(this.InputCNPJ.getText());
            modelFornecedor.setTelefoneFornecedor(this.InputTelefone.getText());
            modelFornecedor.setEmailFornecedor(this.InputEmail.getText());

            if (controllerFornecedor.atualizarFornecedorController(modelFornecedor)) {
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                //CARREGAR CLIENTES NA TABELA
                mostrarFornecedor();
                // InputCodigo.setText("");
                this.habilitaDesabilitaCampos(false);
                this.LimparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar!");
            }

        }

    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDeletarActionPerformed
        // TODO add your handling code here:
        //BOTÃO DELETAR
        try {
            int linha = TabelaFornecedor.getSelectedRow();
            int codigoFornecedor = (int) TabelaFornecedor.getValueAt(linha, 0);
            if (controllerFornecedor.excluirFornecedorController(codigoFornecedor)) {
                JOptionPane.showMessageDialog(this, "Deletado com sucesso");
                this.mostrarFornecedor();
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao deletar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Não existem dados para serem deletados!");
        }

    }//GEN-LAST:event_BtDeletarActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        // TODO add your handling code here:
        // BOTÃO ALTERAR
        try {
            int linha = TabelaFornecedor.getSelectedRow();
            int codigoFornecedor = (int) TabelaFornecedor.getValueAt(linha, 0);
            salvarAlterar = "alterar";
            modelFornecedor = controllerFornecedor.getFornecedorController(codigoFornecedor);
            InputCodigo.setText(String.valueOf(modelFornecedor.getIdFornecedor()));
            InputNome.setText(modelFornecedor.getNomeFornecedor());
            InputCNPJ.setText(modelFornecedor.getCnpjFornecedor());
            InputTelefone.setText(modelFornecedor.getTelefoneFornecedor());
            InputEmail.setText(modelFornecedor.getEmailFornecedor());
            this.habilitaDesabilitaCampos(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecione um item para alterar");
        }


    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        // TODO add your handling code here:
        //BOTÃO NOVO
        this.habilitaDesabilitaCampos(true);
        this.LimparCampos();
        salvarAlterar = "novo";

    }//GEN-LAST:event_BtNovoActionPerformed

    private void mostrarFornecedor() {

        listaModelFornecedor = controllerFornecedor.getListaFornecedorController();
        DefaultTableModel modelo = (DefaultTableModel) TabelaFornecedor.getModel();
        modelo.setNumRows(0);
        int cont = listaModelFornecedor.size();
        for (int i = 0; i < cont; i++) {
      
            modelo.addRow(new Object[]{
                    
                listaModelFornecedor.get(i).getIdFornecedor(),
                listaModelFornecedor.get(i).getNomeFornecedor(),
                listaModelFornecedor.get(i).getCnpjFornecedor(),
                listaModelFornecedor.get(i).getTelefoneFornecedor(),
                listaModelFornecedor.get(i).getEmailFornecedor()
                

            });
        }
    }

    private void habilitaDesabilitaCampos(boolean condicao) {
        InputNome.setEnabled(condicao);
        InputCNPJ.setEnabled(condicao);
        InputTelefone.setEnabled(condicao);
        InputEmail.setEnabled(condicao);
        BtSalvar.setEnabled(condicao);
    }

    private void LimparCampos() {
        InputNome.setText("");
        InputCNPJ.setText("");
        InputTelefone.setText("");
        InputEmail.setText("");
        InputCodigo.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtDeletar;
    private javax.swing.JButton BtNovo;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JTextField InputCNPJ;
    private javax.swing.JTextField InputCodigo;
    private javax.swing.JTextField InputEmail;
    private javax.swing.JTextField InputNome;
    private javax.swing.JTextField InputTelefone;
    private javax.swing.JTable TabelaFornecedor;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
