/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.Model.ModelCliente;
import br.com.Model.ModelOSCliente;
import br.com.Model.ModelServico;
import br.com.controller.ControllerCliente;
import br.com.controller.ControllerOSCliente;
import br.com.controller.ControllerOrdemServico;
import br.com.controller.ControllerServico;
import br.com.controller.ControllerServicosPrestados;
import br.com.model.ModelOrdemServico;
import br.com.model.ModelServicosPrestados;
import br.com.util.FormataData;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LEANDRO
 */
public class ViewOrdemServico extends javax.swing.JFrame {

    /**
     * Creates new form ViewOrdemServico
     */
    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelClientes = new ArrayList<>();
    ControllerServico controllerServico = new ControllerServico();
    ModelServico modelServico = new ModelServico();
    ArrayList<ModelServico> listaModelServico = new ArrayList<>();
    ArrayList<ModelOSCliente> listaModelOSCliente = new ArrayList<>();
    ControllerOSCliente controllerOSCliente = new ControllerOSCliente();
    ControllerOrdemServico controllerOrdemServico = new ControllerOrdemServico();
    ModelOrdemServico modelOrdemServico = new ModelOrdemServico();
    FormataData formataData = new FormataData();
    ControllerServicosPrestados controllerServicosPrestados = new ControllerServicosPrestados();
    ModelServicosPrestados modelServicosPrestados = new ModelServicosPrestados();
    ArrayList<ModelServicosPrestados> listaModelServicosPrestados = new ArrayList<>();

    public ViewOrdemServico() {
        initComponents();
        listarClientes();
        listarServicos();
        carregarOS();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abaConsuExcAlt = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        InputCodCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        InputNomeCliente = new componentes.UJComboBox();
        jLabel2 = new javax.swing.JLabel();
        InputCodigoServico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        InputNomeServico = new componentes.UJComboBox();
        InputQuantidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDados = new javax.swing.JTable();
        btntSalvar = new javax.swing.JButton();
        InputVaalorTotal = new javax.swing.JTextField();
        InputDesconto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaOS = new javax.swing.JTable();
        btDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OS");

        InputCodCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputCodClienteFocusLost(evt);
            }
        });
        InputCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCodClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo do Cliente");

        InputNomeCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                InputNomeClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel2.setText("Nome do Cliente");

        InputCodigoServico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputCodigoServicoFocusLost(evt);
            }
        });
        InputCodigoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCodigoServicoActionPerformed(evt);
            }
        });

        jLabel4.setText("Código serviço");

        InputNomeServico.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                InputNomeServicoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        InputQuantidade.setMinimumSize(new java.awt.Dimension(20, 20));
        InputQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputQuantidadeActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantidade");

        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/Cadastrar.png"))); // NOI18N
        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome Serviço");

        tabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.Servico", "Nome do serviço", "Qtd", "Valor unitário", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaDados);
        if (tabelaDados.getColumnModel().getColumnCount() > 0) {
            tabelaDados.getColumnModel().getColumn(0).setMinWidth(90);
            tabelaDados.getColumnModel().getColumn(0).setPreferredWidth(90);
            tabelaDados.getColumnModel().getColumn(0).setMaxWidth(90);
            tabelaDados.getColumnModel().getColumn(2).setMinWidth(70);
            tabelaDados.getColumnModel().getColumn(2).setPreferredWidth(70);
            tabelaDados.getColumnModel().getColumn(2).setMaxWidth(70);
            tabelaDados.getColumnModel().getColumn(3).setMinWidth(90);
            tabelaDados.getColumnModel().getColumn(3).setPreferredWidth(90);
            tabelaDados.getColumnModel().getColumn(3).setMaxWidth(90);
            tabelaDados.getColumnModel().getColumn(4).setMinWidth(90);
            tabelaDados.getColumnModel().getColumn(4).setPreferredWidth(90);
            tabelaDados.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        btntSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/Salvar.png"))); // NOI18N
        btntSalvar.setText("Salvar");
        btntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntSalvarActionPerformed(evt);
            }
        });

        InputVaalorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputVaalorTotalActionPerformed(evt);
            }
        });

        InputDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputDescontoFocusLost(evt);
            }
        });
        InputDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDescontoActionPerformed(evt);
            }
        });

        jLabel7.setText("Desconto");

        jLabel8.setText("Valor total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btntSalvar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InputCodigoServico, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(InputCodCliente)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel6)
                                            .addComponent(InputNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5)
                                                .addGap(69, 69, 69))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(InputQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(InputNomeServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(InputVaalorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputCodigoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputNomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputVaalorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btntSalvar)
                .addGap(26, 26, 26))
        );

        abaConsuExcAlt.addTab("Cadastro", jPanel1);

        TabelaOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.OS", "Nome do cliente", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelaOS);
        if (TabelaOS.getColumnModel().getColumnCount() > 0) {
            TabelaOS.getColumnModel().getColumn(0).setMinWidth(110);
            TabelaOS.getColumnModel().getColumn(0).setPreferredWidth(110);
            TabelaOS.getColumnModel().getColumn(0).setMaxWidth(110);
            TabelaOS.getColumnModel().getColumn(2).setMinWidth(110);
            TabelaOS.getColumnModel().getColumn(2).setPreferredWidth(110);
            TabelaOS.getColumnModel().getColumn(2).setMaxWidth(110);
        }

        btDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/delete.png"))); // NOI18N
        btDeletar.setText("Deletar");
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDeletar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btDeletar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        abaConsuExcAlt.addTab("Deletar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abaConsuExcAlt)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abaConsuExcAlt)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InputCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCodClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCodClienteActionPerformed

    private void InputCodigoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCodigoServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCodigoServicoActionPerformed

    private void InputQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputQuantidadeActionPerformed

    private void InputDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDescontoActionPerformed

    private void InputVaalorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputVaalorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputVaalorTotalActionPerformed

    private void InputCodClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputCodClienteFocusLost
        // TODO add your handling code here:
        //Input codigo cliente
        modelCliente = controllerCliente.getClienteController(Integer.parseInt(InputCodCliente.getText()));
        InputNomeCliente.setSelectedItem(modelCliente.getNOME_CLIENTE());
    }//GEN-LAST:event_InputCodClienteFocusLost

    private void InputNomeClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_InputNomeClientePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (InputNomeCliente.isPopupVisible()) {
            modelCliente = controllerCliente.getClienteController(InputNomeCliente.getSelectedItem().toString());
            InputCodCliente.setText(String.valueOf(modelCliente.getID_CLIENTE()));
        }
    }//GEN-LAST:event_InputNomeClientePopupMenuWillBecomeInvisible

    private void InputNomeServicoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_InputNomeServicoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (InputNomeServico.isPopupVisible()) {
            modelServico = controllerServico.retornListaServicoController(InputNomeServico.getSelectedItem().toString());
            InputCodigoServico.setText(String.valueOf(modelServico.getID_SERVICO()));
        }
    }//GEN-LAST:event_InputNomeServicoPopupMenuWillBecomeInvisible

    private void InputCodigoServicoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputCodigoServicoFocusLost
        // TODO add your handling code here:
        modelServico = controllerServico.retornListaServicoController(Integer.parseInt(InputCodigoServico.getText()));
        InputNomeServico.setSelectedItem(modelServico.getNOME_SERVICO());
    }//GEN-LAST:event_InputCodigoServicoFocusLost

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        // TODO add your handling code here:
        //BOTÃO DELETAR
        int linha = TabelaOS.getSelectedRow();
        int codigo = (int) TabelaOS.getValueAt(linha, 0);
        try {
           
            controllerServicosPrestados.excluirServicosPrestadosController(codigo);
            if (controllerOrdemServico.excluirOrdemServicoController(codigo)) {
               
                JOptionPane.showMessageDialog(this, "Excluido com sucesso");
                this.carregarOS();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro");
        }
       
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
        //BOTÃO ADICIONAR
        if (InputQuantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        } else {
            modelServico = controllerServico.retornListaServicoController(Integer.parseInt(InputCodigoServico.getText()));
            DefaultTableModel modelo = (DefaultTableModel) tabelaDados.getModel();
            int cont = 0;
            double quantidade;
            quantidade = Double.parseDouble(InputQuantidade.getText());
            for (int i = 0; i < cont; i++) {
                modelo.setNumRows(0);

            }
            modelo.addRow(new Object[]{
                modelServico.getID_SERVICO(),
               modelServico.getNOME_SERVICO(),
                InputQuantidade.getText(),
                modelServico.getVALOR_SERVICO(),
                quantidade * modelServico.getVALOR_SERVICO()
            }
            );
            somarValorTotalServicos();
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void InputDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputDescontoFocusLost
        // TODO add your handling code here:
        somarValorTotalServicos();
    }//GEN-LAST:event_InputDescontoFocusLost

    private void btntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntSalvarActionPerformed
        // TODO add your handling code here:
        //BOTÃO SALVAR
        int codigoDaOrdem = 0;
        listaModelServicosPrestados = new ArrayList<>();

        modelOrdemServico.setIdCliente(Integer.parseInt(InputCodCliente.getText()));
        try {
            modelOrdemServico.setOrdemData(formataData.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
            Logger.getLogger(ViewOrdemServico.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelOrdemServico.setOrdemValorLiquido(Double.parseDouble(InputVaalorTotal.getText()));
        modelOrdemServico.setOrdemValorBruto(Double.parseDouble(InputVaalorTotal.getText()) + Double.parseDouble(InputDesconto.getText()));
        modelOrdemServico.setOrdemValorDesconto(Double.parseDouble(InputDesconto.getText()));

        codigoDaOrdem = controllerOrdemServico.salvarOrdemServicoController(modelOrdemServico);

        if (codigoDaOrdem > 0) {
            JOptionPane.showMessageDialog(null, "Salvo com sucesso");

        } else {
            JOptionPane.showMessageDialog(null, "Erro ao salvar");
        }
        int cont = tabelaDados.getRowCount();
        for (int i = 0; i < cont; i++) {

            modelServicosPrestados = new ModelServicosPrestados();
            modelServicosPrestados.setIdServico((int) tabelaDados.getValueAt(i, 0));
            modelServicosPrestados.setOrdemId(codigoDaOrdem);
            modelServicosPrestados.setValorServico((double) tabelaDados.getValueAt(i, 3));
            modelServicosPrestados.setServicoQuantidade(Integer.parseInt(tabelaDados.getValueAt(i, 2).toString()));
           // modelServicosPrestados.setServicoQuantidade((int) (double) tabelaDados.getValueAt(i, 2));
            listaModelServicosPrestados.add(modelServicosPrestados);
        }
        //SALVAR SERVIÇOS DA VENDA
        if (controllerServicosPrestados.salvarServicosPrestadosController(listaModelServicosPrestados)) {
            JOptionPane.showMessageDialog(null, "Salvo com sucesso");
            carregarOS();
            limparInput();

        } else {
            JOptionPane.showMessageDialog(null, "Erro ao salvar");
        }
    }//GEN-LAST:event_btntSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOrdemServico().setVisible(true);
            }
        });
    }

    //preenche o seletor de clientes
    private void listarClientes() {
        listaModelClientes = controllerCliente.getListaClienteController();
        InputNomeCliente.removeAllItems();
        for (int i = 0; i < listaModelClientes.size(); i++) {
            InputNomeCliente.addItem(listaModelClientes.get(i).getNOME_CLIENTE());
        }

    }

    private void listarServicos() {
        listaModelServico = controllerServico.retornaListaServicoController();
        InputNomeServico.removeAllItems();
        for (int i = 0; i < listaModelServico.size(); i++) {
            InputNomeServico.addItem(listaModelServico.get(i).getNOME_SERVICO());
        }

    }

    private void somarValorTotalServicos() {
        double soma = 0;
        double valor;
        int contador = tabelaDados.getRowCount();
        for (int i = 0; i < contador; i++) {
            valor = (double) tabelaDados.getValueAt(i, 4);
            soma += valor;
        }
        InputVaalorTotal.setText(String.valueOf(soma));
        desconto();
    }

    private void desconto() {
        try {
            InputVaalorTotal.setText(String.valueOf(
                    Double.parseDouble(InputVaalorTotal.getText()) - Double.parseDouble(InputDesconto.getText())));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Preencha de desconto");
        }

    }

    private void carregarOS() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaOS.getModel();
        listaModelOSCliente = controllerOSCliente.getListaOSClienteController();
        int cont = listaModelOSCliente.size();
        modelo.setNumRows(0);
        for (int i = 0; i < cont; i++) {

            modelo.addRow(new Object[]{
                listaModelOSCliente.get(i).getModelOrdemServico().getOrdemId(),
                listaModelOSCliente.get(i).getModelCliente().getNOME_CLIENTE(),
              
                listaModelOSCliente.get(i).getModelOrdemServico().getOrdemData()

            });
        }

    }

    private void limparInput() {
        InputQuantidade.setText("");
        InputDesconto.setText("");
        InputVaalorTotal.setText("");
        DefaultTableModel modelo = (DefaultTableModel) tabelaDados.getModel();
        modelo.setNumRows(0);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputCodCliente;
    private javax.swing.JTextField InputCodigoServico;
    private javax.swing.JTextField InputDesconto;
    private componentes.UJComboBox InputNomeCliente;
    private componentes.UJComboBox InputNomeServico;
    private javax.swing.JTextField InputQuantidade;
    private javax.swing.JTextField InputVaalorTotal;
    private javax.swing.JTable TabelaOS;
    private javax.swing.JTabbedPane abaConsuExcAlt;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btntSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaDados;
    // End of variables declaration//GEN-END:variables
}
