/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.Model.ModelServico;
import br.com.controller.ControllerServico;
import br.com.util.Formatador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;

/**
 *
 * @author LEANDRO
 */
public class ViewServico extends javax.swing.JFrame {

    /**
     * Creates new form ViewServico
     */
    ArrayList<ModelServico> ListaModelServico = new ArrayList<>();
    ControllerServico controlerServico = new ControllerServico();
    ModelServico modelServico = new ModelServico();
    Formatador formatador = new Formatador();
    String salvarAlteração;
    
    public ViewServico() {
        initComponents();
        mostrarServicos();
        setLocationRelativeTo(null);
        habilitaDesabilitaInputs(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InputCodigoServico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InputNomeServico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaServico = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        InputPesquisarServico = new javax.swing.JTextField();
        BtPesquisar = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        BtNovo = new javax.swing.JButton();
        BtDeletar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        InputValorServico = new javax.swing.JFormattedTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Serviços");

        jPanel1.setToolTipText("");

        jLabel1.setText("Código");

        InputCodigoServico.setEditable(false);
        InputCodigoServico.setEnabled(false);
        InputCodigoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCodigoServicoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("Valor");

        TabelaServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelaServico);

        jLabel4.setText("Pesquisar nome do serviço");

        BtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/buscar .png"))); // NOI18N
        BtPesquisar.setText("Pesquisar");
        BtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarActionPerformed(evt);
            }
        });

        BtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/Excluir.png"))); // NOI18N
        BtCancelar.setText("Cancelar");
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        BtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/Cadastrar.png"))); // NOI18N
        BtNovo.setText("Novo");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });

        BtDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/delete.png"))); // NOI18N
        BtDeletar.setText("Deletar");
        BtDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDeletarActionPerformed(evt);
            }
        });

        BtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/Atualizar.png"))); // NOI18N
        BtAlterar.setText("Alterar");
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Icon/Salvar.png"))); // NOI18N
        BtSalvar.setText("Salvar");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        InputValorServico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtSalvar))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(InputCodigoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(InputNomeServico)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(141, 141, 141))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(InputValorServico)
                                .addGap(19, 19, 19)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(InputPesquisarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtPesquisar)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputCodigoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputNomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPesquisarServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesquisar)
                    .addComponent(InputValorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCancelar)
                    .addComponent(BtNovo)
                    .addComponent(BtDeletar)
                    .addComponent(BtAlterar)
                    .addComponent(BtSalvar))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InputCodigoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCodigoServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCodigoServicoActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        // TODO add your handling code here:
        //BOTÃO SALVAR
      if(salvarAlteração.equals("salvar"))
      { 
      this.salvarServico();
      
      }else if(salvarAlteração.equals("alterar"))
      {
      this.alterarServico();
      }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDeletarActionPerformed
        // TODO add your handling code here:
        //BOTÃO DELETAR
        try {
            
             int linha = TabelaServico.getSelectedRow();
            int codigoServico = (int) TabelaServico.getValueAt(linha,0);
            if(controlerServico.deletarServicoController(codigoServico))
            {
                JOptionPane.showMessageDialog(this, "Dados deletados com sucesso!");
                this.habilitaDesabilitaInputs(false);
                InputNomeServico.setEnabled(false);
                InputValorServico.setEnabled(false);
                this.mostrarServicos();

            }else{
                JOptionPane.showMessageDialog(this, "Erro ao deletar dados!");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Escolha um item para deletar");
        }
       
    }//GEN-LAST:event_BtDeletarActionPerformed

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        // BOTÃO NOVO
             habilitaDesabilitaInputs(true);   
             salvarAlteração ="salvar";
    }//GEN-LAST:event_BtNovoActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        // BOTÃO CANCELAR
        this.habilitaDesabilitaInputs(false);
        this.limparInputs();
        InputCodigoServico.setText("");
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        // BOTÃO ALTERAR
        habilitaDesabilitaInputs(true);
        int linhaAlterar = this.TabelaServico.getSelectedRow();
        salvarAlteração="alterar";        
        try {
            // BUSCA NO BANCO
            int codigoServico = (int) this.TabelaServico.getValueAt(linhaAlterar,0);
            modelServico=controlerServico.retornListaServicoController(codigoServico);
            //JOGAR ITEN SELECIONADO NA INTERFACE
            this.InputCodigoServico.setText(String.valueOf(modelServico.getID_SERVICO()));
            this.InputNomeServico.setText(modelServico.getNOME_SERVICO());
            this.InputValorServico.setText(String.valueOf(modelServico.getVALOR_SERVICO()));
          
        } catch (Exception e) {
            habilitaDesabilitaInputs(false);
            JOptionPane.showMessageDialog(this,"Erro ao alterar!");
        }
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarActionPerformed
        // BOTÃO PESQUISAR
        DefaultTableModel modelo = (DefaultTableModel) this.TabelaServico.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.TabelaServico.setRowSorter(classificador);
        String texto = InputPesquisarServico.getText();
        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
        
    }//GEN-LAST:event_BtPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewServico().setVisible(true);
            }
        });
    }
    //HABILITA OS CAMPOS
    private void habilitaDesabilitaInputs(boolean condicao)
    {
        
        InputNomeServico.setEnabled(condicao);
        InputValorServico.setEnabled(condicao);
        BtSalvar.setEnabled(condicao);
    }
    //LIMPA OS CAMPOS
    private void limparInputs()
    {
        InputNomeServico.setText("");
        InputValorServico.setText("");
    }
    
    private void salvarServico()
    {
        //METODO QUE SALVA OS SERVIÇOS
          modelServico.setNOME_SERVICO(this.InputNomeServico.getText());
          modelServico.setVALOR_SERVICO(formatador.converterVirgulaParaPonto(this.InputValorServico.getText()));
        if (controlerServico.cadastraServicoController(modelServico)>0)
        {
            JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!");
             this.limparInputs();
             InputNomeServico.setEnabled(false);
             InputValorServico.setEnabled(false);
             habilitaDesabilitaInputs(false);
            mostrarServicos();
        }else{
            JOptionPane.showMessageDialog(this,"Erro ao cadastrar dados!");
        }
    }
    
    private void alterarServico()
    {
        //METODO QUE ALTERA OS SERVIÇOS
         modelServico.setNOME_SERVICO(this.InputNomeServico.getText());
         modelServico.setVALOR_SERVICO(formatador.converterVirgulaParaPonto(this.InputValorServico.getText()));
        if (controlerServico.alterarServicoController(modelServico))
        {
            JOptionPane.showMessageDialog(this, "Dados Alterados com sucesso!");
             this.limparInputs();
             InputNomeServico.setEnabled(false);
             InputValorServico.setEnabled(false);
             InputCodigoServico.setText("");
              habilitaDesabilitaInputs(false);
            mostrarServicos();
        }else{
            JOptionPane.showMessageDialog(this,"Erro ao alterar dados!");
        }
        
    }
    
    //JOGA OS SERVIÇOS NA TABELA

    private void mostrarServicos() {
        ListaModelServico = controlerServico.retornaListaServicoController();
        DefaultTableModel modelo = (DefaultTableModel) TabelaServico.getModel();
        modelo.setNumRows(0);
        int contador = ListaModelServico.size();
        for (int i = 0; i < contador; i++) {

            modelo.addRow(new Object[]{
                ListaModelServico.get(i).getID_SERVICO(),
                ListaModelServico.get(i).getNOME_SERVICO(),
                ListaModelServico.get(i).getVALOR_SERVICO()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtDeletar;
    private javax.swing.JButton BtNovo;
    private javax.swing.JButton BtPesquisar;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JTextField InputCodigoServico;
    private javax.swing.JTextField InputNomeServico;
    private javax.swing.JTextField InputPesquisarServico;
    private javax.swing.JFormattedTextField InputValorServico;
    private javax.swing.JTable TabelaServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
